version: "3.8"
services:
  app:
    container_name: my_symfony
    build:
      dockerfile: ./services/app/Dockerfile
      context: ./
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/var
    ports:
      - 8888:80
