index:
    path: /
    controller: 'App\Controller\DefaultController::index'
hello:
    path: /hello/{name}
    controller: 'App\Controller\DefaultController::hello'
lucky:
    path: /lucky/number
    controller: 'App\Controller\LuckyController::number'
